# Pandas
pandas is a open source library for data frames and data analysis tools

In [1]:
import pandas as pd
import numpy as np

In [2]:
np.arange(0,20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [6]:
arr1 =np.arange(0,20).reshape(5,4)

In [7]:
print(arr1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [11]:
df = pd.DataFrame(arr1,index=['index1','index2','index3','index4','index5'],columns=['col1','col2','col3','col4'])

In [12]:
df

col1  col2  col3  col4
index1     0     1     2     3
index2     4     5     6     7
index3     8     9    10    11
index4    12    13    14    15
index5    16    17    18    19

In [13]:
df.head()

col1  col2  col3  col4
index1     0     1     2     3
index2     4     5     6     7
index3     8     9    10    11
index4    12    13    14    15
index5    16    17    18    19

In [14]:
df.loc['index1']

col1    0
col2    1
col3    2
col4    3
Name: index1, dtype: int32

In [18]:
df.iloc[1:3,1:3]

col2  col3
index2     5     6
index3     9    10

In [19]:
df['col2'].value_counts()

13    1
5     1
17    1
9     1
1     1
Name: col2, dtype: int64

In [21]:
dataset = pd.read_csv(r'C:\Users\mraje\Documents\krish naiks ds\EDA1-master\EDA1-master\titanic_train.csv')

In [22]:
dataset.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [23]:
dataset

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, index1 to index5
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col1    5 non-null      int32
 1   col2    5 non-null      int32
 2   col3    5 non-null      int32
 3   col4    5 non-null      int32
dtypes: int32(4)
memory usage: 280.0+ bytes


In [25]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [26]:
dataset.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [28]:
df.describe()

col1       col2       col3       col4
count   5.000000   5.000000   5.000000   5.000000
mean    8.000000   9.000000  10.000000  11.000000
std     6.324555   6.324555   6.324555   6.324555
min     0.000000   1.000000   2.000000   3.000000
25%     4.000000   5.000000   6.000000   7.000000
50%     8.000000   9.000000  10.000000  11.000000
75%    12.000000  13.000000  14.000000  15.000000
max    16.000000  17.000000  18.000000  19.000000

In [29]:
dataset['Survived'].value_counts()

0    549
1    342
Name: Survived, dtype: int64

In [30]:
dataset['Pclass'].value_counts()

3    491
1    216
2    184
Name: Pclass, dtype: int64

In [31]:
dataset[dataset['Fare']>60]

PassengerId  Survived  Pclass  \
1              2         1       1   
27            28         0       1   
31            32         1       1   
34            35         0       1   
52            53         1       1   
..           ...       ...     ...   
846          847         0       3   
849          850         1       1   
856          857         1       1   
863          864         0       3   
879          880         1       1   

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
27                      Fortune, Mr. Charles Alexander    male  19.0      3   
31      Spencer, Mrs. William Augustus (Marie Eugenie)  female   NaN      1   
34                             Meyer, Mr. Edgar Joseph    male  28.0      1   
52            Harper, Mrs. Henry Sleeper (Myna Haxtun)  female  49.0      1   
..                                                 ...     ...   ...    ...   
846                           Sage, Mr. Douglas Bullen    male   NaN      8   
849       Goldenberg, Mrs. Samuel L (Edwiga Grabowska)  female   NaN      1   
856         Wick, Mrs. George Dennick (Mary Hitchcock)  female  45.0      1   
863                  Sage, Miss. Dorothy Edith "Dolly"  female   NaN      8   
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  female  56.0      0   

     Parch    Ticket      Fare        Cabin Embarked  
1        0  PC 17599   71.2833          C85        C  
27       2     19950  263.0000  C23 C25 C27        S  
31       0  PC 17569  146.5208          B78        C  
34       0  PC 17604   82.1708          NaN        C  
52       0  PC 17572   76.7292          D33        C  
..     ...       ...       ...          ...      ...  
846      2  CA. 2343   69.5500          NaN        S  
849      0     17453   89.1042          C92        C  
856      1     36928  164.8667          NaN        S  
863      2  CA. 2343   69.5500          NaN        S  
879      1     11767   83.1583          C50        C  

[122 rows x 12 columns]

In [32]:
lst_data=[[1,2,3],[3,4,np.nan],[5,6,np.nan],[np.nan,np.nan,np.nan]]

In [33]:
lst_data

[[1, 2, 3], [3, 4, nan], [5, 6, nan], [nan, nan, nan]]

In [35]:
df2=pd.DataFrame(lst_data)

In [36]:
df2

0    1    2
0  1.0  2.0  3.0
1  3.0  4.0  NaN
2  5.0  6.0  NaN
3  NaN  NaN  NaN

In [38]:
df2.dropna()

0    1    2
0  1.0  2.0  3.0

In [42]:
df2.dropna(axis=0)

0    1    2
0  1.0  2.0  3.0

In [43]:
df2.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3]

In [44]:
#it shows the values of nan as true
pd.isna(df2)

0      1      2
0  False  False  False
1  False  False   True
2  False  False   True
3   True   True   True

In [45]:
#it shows the nan values as false
df2.notna()

0      1      2
0   True   True   True
1   True   True  False
2   True   True  False
3  False  False  False

In [46]:
dataset['Name']

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...                        
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [47]:
dataset['Name'].values

array(['Braund, Mr. Owen Harris',
       'Cumings, Mrs. John Bradley (Florence Briggs Thayer)',
       'Heikkinen, Miss. Laina',
       'Futrelle, Mrs. Jacques Heath (Lily May Peel)',
       'Allen, Mr. William Henry', 'Moran, Mr. James',
       'McCarthy, Mr. Timothy J', 'Palsson, Master. Gosta Leonard',
       'Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)',
       'Nasser, Mrs. Nicholas (Adele Achem)',
       'Sandstrom, Miss. Marguerite Rut', 'Bonnell, Miss. Elizabeth',
       'Saundercock, Mr. William Henry', 'Andersson, Mr. Anders Johan',
       'Vestrom, Miss. Hulda Amanda Adolfina',
       'Hewlett, Mrs. (Mary D Kingcome) ', 'Rice, Master. Eugene',
       'Williams, Mr. Charles Eugene',
       'Vander Planke, Mrs. Julius (Emelia Maria Vandemoortele)',
       'Masselmani, Mrs. Fatima', 'Fynney, Mr. Joseph J',
       'Beesley, Mr. Lawrence', 'McGowan, Miss. Anna "Annie"',
       'Sloper, Mr. William Thompson', 'Palsson, Miss. Torborg Danira',
       'Asplund, Mrs. Carl Oscar 

In [48]:
df2[1].values

array([ 2.,  4.,  6., nan])

In [56]:
data = ('col1,col2,col3\n'
            'x,y,1\n'
            'a,b,2\n'
            'c,d,3')

In [57]:
pd.read_csv(StringIO(data))

col1 col2  col3
0    x    y     1
1    a    b     2
2    c    d     3

In [55]:
from io import StringIO, BytesIO
pd.read_csv(StringIO(data), usecols=lambda x: x.upper() in ['COL1', 'COL3'])

col1  col3
0    x     1
1    a     2
2    c     3

In [62]:
dd =pd.read_csv(StringIO(data),usecols=['col1','col3'])
dd

col1  col3
0    x     1
1    a     2
2    c     3

In [63]:
dd['col1'][1]

'a'

In [64]:
dd.dtypes

col1    object
col3     int64
dtype: object

In [65]:
data = ('index,a,b,c\n'
           '4,apple,bat,5.7\n'
            '8,orange,cow,10')
data

'index,a,b,c\n4,apple,bat,5.7\n8,orange,cow,10'

In [66]:
pd.read_csv(StringIO(data))

index       a    b     c
0      4   apple  bat   5.7
1      8  orange  cow  10.0

In [67]:
pd.read_csv(StringIO(data),index_col=0)

a    b     c
index                   
4       apple  bat   5.7
8      orange  cow  10.0

In [68]:
pd.read_csv(StringIO(data),index_col=False)

index       a    b     c
0      4   apple  bat   5.7
1      8  orange  cow  10.0

In [70]:
## Combining usecols and index_col
data = ('a,b,c\n'
           '4,apple,bat,\n'
            '8,orange,cow,')
    
data
    
    

'a,b,c\n4,apple,bat,\n8,orange,cow,'

In [75]:
pd.read_csv(StringIO(data),usecols=['b','c'])
##here pd function too 4 and 8 into index column and a values as apple and orange and b values as bat cow but here we didnt give any indexing

b   c
4  bat NaN
8  cow NaN

In [76]:
pd.read_csv(StringIO(data),usecols=['b','c'],index_col=False)

b    c
0   apple  bat
1  orange  cow

In [77]:
## Quoting and Escape Characters¶. Very useful in NLP

data = 'a,b\n"hello, \\"Bob\\", nice to see you",5'

In [78]:
pd.read_csv(StringIO(data),escapechar='\\')

a  b
0  hello, "Bob", nice to see you  5

In [82]:
## URL to CSV

df=pd.read_csv('https://download.bls.gov/pub/time.series/cu/cu.item',
                 sep='\t')

In [80]:
df

item_code                                          item_name  \
0         AA0                               All items - old base   
1        AA0R  Purchasing power of the consumer dollar - old ...   
2         SA0                                          All items   
3        SA0E                                             Energy   
4       SA0L1                                All items less food   
..        ...                                                ...   
394   SS68023   Tax return preparation and other accounting fees   
395   SSEA011                                  College textbooks   
396  SSFV031A           Food at elementary and secondary schools   
397   SSGE013                                 Infants' equipment   
398   SSHJ031                                 Infants' furniture   

     display_level selectable  sort_sequence  
0                0          T              2  
1                0          T            399  
2                0          T              1  
3                1          T            374  
4                1          T            358  
..             ...        ...            ...  
394              4          T            352  
395              3          T            314  
396              3          T            122  
397              3          T            355  
398              3          T            165  

[399 rows x 5 columns]

In [84]:
## Read Json to CSV
data = '{"employee_name": "James", "email": "james@gmail.com", "job_profile": [{"title1":"Team Lead", "title2":"Sr. Developer"}]}'
pd.read_json(data)

employee_name            email  \
0         James  james@gmail.com   

                                         job_profile  
0  {'title1': 'Team Lead', 'title2': 'Sr. Develop...

In [93]:
df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data', header=None)

In [94]:
df

0      1     2     3     4    5     6     7     8     9      10    11  \
0     1  14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29   5.64  1.04   
1     1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28   4.38  1.05   
2     1  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81   5.68  1.03   
3     1  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18   7.80  0.86   
4     1  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82   4.32  1.04   
..   ..    ...   ...   ...   ...  ...   ...   ...   ...   ...    ...   ...   
173   3  13.71  5.65  2.45  20.5   95  1.68  0.61  0.52  1.06   7.70  0.64   
174   3  13.40  3.91  2.48  23.0  102  1.80  0.75  0.43  1.41   7.30  0.70   
175   3  13.27  4.28  2.26  20.0  120  1.59  0.69  0.43  1.35  10.20  0.59   
176   3  13.17  2.59  2.37  20.0  120  1.65  0.68  0.53  1.46   9.30  0.60   
177   3  14.13  4.10  2.74  24.5   96  2.05  0.76  0.56  1.35   9.20  0.61   

       12    13  
0    3.92  1065  
1    3.40  1050  
2    3.17  1185  
3    3.45  1480  
4    2.93   735  
..    ...   ...  
173  1.74   740  
174  1.56   750  
175  1.56   835  
176  1.62   840  
177  1.60   560  

[178 rows x 14 columns]

In [95]:
df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data')

In [96]:
df
## in this the first row merged into header because there is no header in the table

1  14.23  1.71  2.43  15.6  127   2.8  3.06   .28  2.29   5.64  1.04  \
0    1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28   4.38  1.05   
1    1  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81   5.68  1.03   
2    1  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18   7.80  0.86   
3    1  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82   4.32  1.04   
4    1  14.20  1.76  2.45  15.2  112  3.27  3.39  0.34  1.97   6.75  1.05   
..  ..    ...   ...   ...   ...  ...   ...   ...   ...   ...    ...   ...   
172  3  13.71  5.65  2.45  20.5   95  1.68  0.61  0.52  1.06   7.70  0.64   
173  3  13.40  3.91  2.48  23.0  102  1.80  0.75  0.43  1.41   7.30  0.70   
174  3  13.27  4.28  2.26  20.0  120  1.59  0.69  0.43  1.35  10.20  0.59   
175  3  13.17  2.59  2.37  20.0  120  1.65  0.68  0.53  1.46   9.30  0.60   
176  3  14.13  4.10  2.74  24.5   96  2.05  0.76  0.56  1.35   9.20  0.61   

     3.92  1065  
0    3.40  1050  
1    3.17  1185  
2    3.45  1480  
3    2.93   735  
4    2.85  1450  
..    ...   ...  
172  1.74   740  
173  1.56   750  
174  1.56   835  
175  1.62   840  
176  1.60   560  

[177 rows x 14 columns]

In [100]:
#convert json to csv
data = '{"employee_name": "James", "email": "james@gmail.com", "job_profile": [{"title1":"Team Lead", "title2":"Sr. Developer"}]}'
dd= pd.read_json(data)
dd

employee_name            email  \
0         James  james@gmail.com   

                                         job_profile  
0  {'title1': 'Team Lead', 'title2': 'Sr. Develop...

In [101]:
dd.to_csv('empldata.csv')

In [102]:
dd

employee_name            email  \
0         James  james@gmail.com   

                                         job_profile  
0  {'title1': 'Team Lead', 'title2': 'Sr. Develop...

In [103]:
type(dd)

pandas.core.frame.DataFrame

In [105]:
dd.to_json(orient='index')

'{"0":{"employee_name":"James","email":"james@gmail.com","job_profile":{"title1":"Team Lead","title2":"Sr. Developer"}}}'

In [106]:
dd.to_json()

'{"employee_name":{"0":"James"},"email":{"0":"james@gmail.com"},"job_profile":{"0":{"title1":"Team Lead","title2":"Sr. Developer"}}}'

In [107]:
dd.to_json(orient='records')

'[{"employee_name":"James","email":"james@gmail.com","job_profile":{"title1":"Team Lead","title2":"Sr. Developer"}}]'

In [112]:
url = 'https://www.fdic.gov/resources/resolutions/bank-failures/failed-bank-list/'

dfs = pd.read_html(url)

In [113]:
dfs

[                         Bank NameBank           CityCity StateSt  CertCert  \
 0                    Almena State Bank             Almena      KS     15426   
 1           First City Bank of Florida  Fort Walton Beach      FL     16748   
 2                 The First State Bank      Barboursville      WV     14361   
 3                   Ericson State Bank            Ericson      NE     18265   
 4     City National Bank of New Jersey             Newark      NJ     21111   
 ..                                 ...                ...     ...       ...   
 558                 Superior Bank, FSB           Hinsdale      IL     32646   
 559                Malta National Bank              Malta      OH      6629   
 560    First Alliance Bank & Trust Co.         Manchester      NH     34264   
 561  National State Bank of Metropolis         Metropolis      IL      3815   
 562                   Bank of Honolulu           Honolulu      HI     21029   
 
                  Acquiring Institutio

In [117]:
dfs[0]

Bank NameBank           CityCity StateSt  CertCert  \
0                    Almena State Bank             Almena      KS     15426   
1           First City Bank of Florida  Fort Walton Beach      FL     16748   
2                 The First State Bank      Barboursville      WV     14361   
3                   Ericson State Bank            Ericson      NE     18265   
4     City National Bank of New Jersey             Newark      NJ     21111   
..                                 ...                ...     ...       ...   
558                 Superior Bank, FSB           Hinsdale      IL     32646   
559                Malta National Bank              Malta      OH      6629   
560    First Alliance Bank & Trust Co.         Manchester      NH     34264   
561  National State Bank of Metropolis         Metropolis      IL      3815   
562                   Bank of Honolulu           Honolulu      HI     21029   

                 Acquiring InstitutionAI Closing DateClosing  FundFund  
0                            Equity Bank    October 23, 2020     10538  
1              United Fidelity Bank, fsb    October 16, 2020     10537  
2                         MVB Bank, Inc.       April 3, 2020     10536  
3             Farmers and Merchants Bank   February 14, 2020     10535  
4                        Industrial Bank    November 1, 2019     10534  
..                                   ...                 ...       ...  
558                Superior Federal, FSB       July 27, 2001      6004  
559                    North Valley Bank         May 3, 2001      4648  
560  Southern New Hampshire Bank & Trust    February 2, 2001      4647  
561              Banterra Bank of Marion   December 14, 2000      4646  
562                   Bank of the Orient    October 13, 2000      4645  

[563 rows x 7 columns]

# saving dataset onto hard drive

In [119]:
data = ('col1,col2,col3\n'
            'x,y,1\n'
            'a,b,2\n'
            'c,d,3')
data

'col1,col2,col3\nx,y,1\na,b,2\nc,d,3'

In [120]:
df = pd.read_csv(StringIO(data))
df

col1 col2  col3
0    x    y     1
1    a    b     2
2    c    d     3

In [121]:
df.to_pickle('data_sample')

In [122]:
pd.read_pickle('data_sample')

col1 col2  col3
0    x    y     1
1    a    b     2
2    c    d     3